# Generated by Django 5.0 on 2023-12-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.BooleanField(default=False, verbose_name='finalizado'),
        ),
    ]
